### ISSUE TITLE
Interfacing via go generate

### ISSUE THREAD

**Issue by mishak87** [redefiance/gotemplate#1]
Using go generate user would not have to use template_impl.go to declare types just reference them in comments in another package file where they are is used or next to wrapped imported type.

Example (writing from head):
```go
package main
import (
    "ioutils"
)

// go:generate gotemplate template.go File
type File ioutils.File
```

**Comment by redefiance** [comment]
See https://github.com/ncw/gotemplate for a go:generate based approach.
I decided to go with a less powerful, but (in my opinion) easier to use version that doesn't use magic comments.

**Comment by mishak87** [comment]
Thanks!
